# HTTP Server
server:
  port: 8888

 # Spring Cloud Config Server Repository
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/miguelcamachodevcastores/microservices-config-store
          default-label: main


  # Spring properties in case you use different profiles
  #profiles:
  #  active: dev
